version: '3.8'

services:
  app:
    build: .
    container_name: hotel_booking_java
    restart: always
    ports:
      - "8091:8091"
    networks:
      - default  # dùng default network của docker-compose

networks:
  default:
