version: '3.8'

services:
  app:
    build: .
    container_name: hotel_booking_java
    restart: always
#    environment:
#      - ENV=production
    ports:
      - "8091:8091"
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'

      # Cấu hình HTTP
      - 'traefik.http.routers.hotel.entrypoints=http'
      - 'traefik.http.routers.hotel.rule=Host(`java.thepointsaver.com`)'
      - "traefik.http.routers.hotel.service=hotel-service"


      # Cấu hình HTTPS
      - 'traefik.http.routers.hotel-secure.entrypoints=https'
      - 'traefik.http.routers.hotel-secure.rule=Host(`java.thepointsaver.com`)'
      - 'traefik.http.routers.hotel-secure.tls.certresolver=letsencrypt'

      # Chuyển tiếp yêu cầu đến container Spring Boot
      - "traefik.http.services.hotel-service.loadbalancer.server.port=8091"

    networks:
      - traefik

networks:
  traefik:
    external: true
