name: Deploy Java to VPS Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy back end to VPS
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        PASS: ${{ secrets.PASS }}
     
        
      run: |
     
        
        # SSH into VPS to extract and deploy
        sshpass -p $PASS ssh -T -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << EOF
          cd /home/$VPS_USER
          
       
        
        
          git clone git@github.com:khoidang2110/hotel-booking-java.git  
          cd hotel-booking-java || exit
              # Dừng và xoá container cũ
          docker-compose down || true

          # Xoá image cũ
          docker rmi -f hotel-booking-java || true  

          # Chạy container mới
          docker-compose up -d --build

          # Dọn dẹp thư mục
          cd ..
          rm -rf hotel-booking-java
          docker image prune -f
        EOF
